### ISSUE TITLE
Video download cannot complete

### ISSUE THREAD

**Issue by infodavid** [gaganpreet/udemy-dl#29]
When I download the video, the backmost video size is only 110KB. 

Hope you could help us fix it.

Thanks a lot!

**Comment by gaganpreet** [comment]
Does this happen on one course only? I recently saw a course which had some videos hosted on Youtube. The script will only download videos which are hosted directly by Udemy. Can you check if the course you have this issue on has videos on Youtube?

**Comment by cryptofuture** [comment]
Hi. Could we redirect curl to youtube-dl instead if youtube is detected in url?
