### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Eloquenz** [gaganpreet/udemy-dl#30]
Hey guys,

I got the script running, but If i try to download a course I always got an IOError.

CMD is giving out: 
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

I tried adding '-k' to the curl method (Python27\Lib\site-packages\udemy_dl\udemy_dl.py), but for me it doesn't work.

Is there a temporarily fix?

Regards

**Comment by gaganpreet** [comment]
This is not related to the curl command being used to download the file, but the requests library. If you want a temporary (insecure) solution, change the get and post methods in your file, lines 34 and 37

Highlighted here: https://github.com/gaganpreet/udemy-dl/blob/38f438942e022f867da63c1b3ac93dc245ee4ad8/src/udemy_dl/udemy_dl.py#L33-37

add `, verify=False` after `headers=self.headers`

**Comment by Eloquenz** [comment]
You sir, are great! Thank you very much! I will try this :)

**Comment by gaganpreet** [comment]
Tracking this issue in #32 because it has more info
