### ISSUE TITLE
[Question] Tricky headers

### ISSUE THREAD

**Issue by mr-coder** [gaganpreet/udemy-dl#35]
Hi contributors,

Many thanks for this useful script. It's not an issue really as I said in title.I saw two tricky headers `X-Udemy-Bearer-Token` and `X-Udemy-Bearer-Token` are set and send through script which I couldn't locate on live sent headers.

I'm so curious to know how these headers are found out. Any clarifications are appreciated. Thank you

**Comment by gaganpreet** [comment]
I added these headers back in #13 when udemy changed their API. As to how I found these out - I used the network tab in the browser and saw the two new headers and figured these were the ones causing the failed authorization error and everything else in the request had stayed the same. Hope this helps. :)
