### ISSUE TITLE
[Error] Error on Input

### ISSUE THREAD

**Issue by gh0stl4b** [gaganpreet/udemy-dl#36]
I have absolutely no idea what caused this error, first time using this app, btw =)
Would be a great feature to add a --verbose option to the app
```
udemy-dl -u MY_USERNAME -p MY_PASSWORD https://www.udemy.com/complete-ios-developer-course/                                                                                                  
Downloading to: ~/Downloads/complete-ios-developer-course

Error on Input
```

**Comment by gaganpreet** [comment]
"Error on Input" comes from udemy when your login details are wrong. Maybe you're entering the correct password but due to special characters it could not be interpreted correctly by the script. I'd suggest you run the script without the `-u`/`-p` parameters and enter those details in the script prompt like this:

    udemy-dl https://www.udemy.com/complete-ios-developer-course/

**Comment by gh0stl4b** [comment]
Tried that already, and it gives me the same output unfortunately, tried logging in to Udemy itself to check the credentials, everything works out...
I am now thinking that I should create a second account with a simple username and password and see if it will work on a free course.

**Comment by gaganpreet** [comment]
Would it be possible for you to edit this line:

**Comment by gh0stl4b** [comment]
I've managed to figure out why it did not want to log me in that time, one again proving to myself that I am   an idiot =) When I was logging in from the console I entered the username all lowercase, as for the webpage I was logging in and the username was already entered correctly with uppercase and lowercase letters...

So I guess problem solved, I just need to pay a bit more attention to things that I enter =)
Thanks, and sorry for disturbing you.

PS: I still would implement a verbose output if I were you =)

**Comment by gaganpreet** [comment]
I'm planning a refactor to better reorganize things and then the verbose option will be available. Glad you figured out your issue though. :-)

**Comment by sammytech001** [comment]
Hello gaganpreet, i will like to chat or write you email, can you please write me at sammytech1212@gmail.com

**Comment by SivaMamabakkam** [comment]
Is the character "1" considered illegal in password... Here is the response I am seeing.. my username and password are correct and verified ..

{u'error': {u'data': {u'formErrors': u'Please check your email and password.', u'itemErrors': []}, u'message': u'Error on Input', u'code': 401, u'type': None}}

**Comment by sammytech001** [comment]
can you check a file for me?  i bought it i was told it can bypass udemy
paid course and download the videos. please can you check the file and
correct it for me. i think it as some errors  please check if you can amend
it for me please..

http://www.4shared.com/office/YQrZw5hdce/1py.html?

**Comment by rinodung** [comment]
You should rename udemy-dl to udemy-dl.py and run it in script folder
