### ISSUE TITLE
Solution to CA certificate

### ISSUE THREAD

**Issue by gtrabanco** [gaganpreet/udemy-dl#57]
Follow the steps in:
https://github.com/gaganpreet/udemy-dl/issues/48

Follow the steps in this video:
https://www.youtube.com/watch?v=iwqC4RrU-AY

--- The steps in the video are: ---
1) Add this line after "import requests"
import requests.sessions

2) Modify the line "self.session = requests.Session()" in the first __init__ to:
self.session = requests.sessions.Session()

Now it is running on Mac OS X 10.10.3
NOTE: If you're on Mac you have to modify the files on the path:
/Library/Python/2.7/site-packages/udemy_dl

For youtube videos just install youtube-dl like it was udemy-dl package...

**Comment by zydrick** [comment]
For youtube videos just install youtube-dl like it was udemy-dl package...

**Comment by gaganpreet** [comment]
This change is now in master.
