### ISSUE TITLE
Help for Windows Users

### ISSUE THREAD

**Issue by sinip1** [gaganpreet/udemy-dl#60]
This is not actually an issue with the program itself but could someone explain how to make it work in Windows environment? I mean I've installed Python 3.4 and the rest of the things (I think) including this program as well (ended up in Python34\Lib\site-packages\, but how do I actually make it work?

Thanks in advance!

**Comment by camagenta** [comment]
Hi Sinip1,

This video may help you : https://youtu.be/6wgykHNp6vQ

For short
1. Install python
2. Edit environtment variable. 
Variable Name = PATH
Variable Value = C:\Python34\;C:\Python34\Scripts
3. Open cmd / powershell
4. cd to C:\Python34\Scripts
5. run ==> pip install udemy-dl
6. rename udemy-dl to udemy.dl.py
7. You are set. try run ==> udemy.dl https://www.udemy.com/python-3-for-beginners/

**Comment by sinip1** [comment]
Thanks. I've already stumbled upon that video few days ago. Nicely explained, works perfectly.
