### ISSUE TITLE
Google+ Login failure

### ISSUE THREAD

**Issue by msj2** [gaganpreet/udemy-dl#66]
Hi GaganPreet, I login to udemy using Google+....
When I run udemy-dl in command prompt giving my google+ userid & passwd, I get error "Error on input".

Can you help?

**Comment by meatcomputer** [comment]
Go to Udemy and reset the password for your account using your gmail as the account name. Then use the new Udemy password.

**Comment by wfalkwallace** [comment]
@meatcomputer I still get "Error on input" :neutral_face:

**Comment by stevehorn** [comment]
Log into Udemy. Click on edit account, then click on the Account link in the left-hand menu. Enter a password and click change password. 

This worked for me when I had initially created my account by linking with Facebook.

**Comment by msj2** [comment]
Thanks Meatcomputer. user id = gmail id, password = <as you mentioned>  
This worked like a breeze.

Thank you.
