### ISSUE TITLE
error with new build?

### ISSUE THREAD

**Issue by noph34r** [gaganpreet/udemy-dl#67]
it's always saying
C:\Python27\Lib\site-packages\udemy_dl>C:\Python27\python.exe C:\Python27\Lib\site-packages\udemy_dl\udemy_dl.py https://www.udemy.com/evergreen-empir
e/
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\udemy_dl\udemy_dl.py", line 12, in <module>
    from .download import download, DLException
ValueError: Attempted relative import in non-package

just update it to newest build and happens to get this
not really familiar to python myself

**Comment by aml36605** [comment]
got almost same issue with Python 343

my files after installing and rename udemy-dl to udemy-dl.py (1kb) file

![image](https://cloud.githubusercontent.com/assets/5436905/7896208/9f58ab7c-06b1-11e5-8eb6-369baf41a4f1.png)

![image](https://cloud.githubusercontent.com/assets/5436905/7896211/c70d8e44-06b1-11e5-8b34-2000e86f02f1.png)


some help is needed .....

**Comment by gaganpreet** [comment]
I don't use Windows, but the script should work without any changes to the files. Look at #60 for a solution.
