### ISSUE TITLE
Hi! Downloading slow...

### ISSUE THREAD

**Issue by ArtCC** [gaganpreet/udemy-dl#69]
Hi! I can only download one or two videos, then slows to 10 kb/s. Do you know why can this happen?

**Comment by gaganpreet** [comment]
The script doesn't implement any throttling, so it either has to be your internet connection or udemy preventing you from downloading too much. Unfortunately, I can't do anything about that at all.

**Comment by ArtCC** [comment]
Ok! Thank you very much. Your job is fantastic :)
