### ISSUE TITLE
Could not download videos anymore?

### ISSUE THREAD

**Issue by gvimlan95** [gaganpreet/udemy-dl#75]
This is the output here:

Traceback (most recent call last):
  File "/usr/local/bin/UDEMY-DL", line 5, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 195, in main
    udemy_dl(username, password, link, output_dir)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 142, in udemy_dl
    login(username, password)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 45, in login
    csrf_token = get_csrf_token()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 41, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by NANO-Chile** [comment]
Im getting the exact same problem, please HELP!

**Comment by sahilsk** [comment]
same here :(

**Comment by nishad** [comment]
Seems like udemy changed login pages. `csrfmiddlewaretoken` is introduced instead of `csrf` and it throws up `CSRF verification failed. Request aborted.` Now udemy sets `csrftoken` cookie as well.

**Comment by NANO-Chile** [comment]
nishad you think is possible to fix the situation?

**Comment by nishad** [comment]
I guess @gaganpreet can fix it easily. Let's wait for his response.

**Comment by raouf30** [comment]
@gaganpreet kindly help as getting exact same issue with the verification.

**Comment by Alaswadi** [comment]
same problem here!!

**Comment by finalight** [comment]
please fix this problem thanks

**Comment by badershs** [comment]
I have the same problem could you fix it please  ? ?

**Comment by ozgurdemirel** [comment]
same

**Comment by sinip1** [comment]
Yep, just hit into the same issue.

**Comment by runner989** [comment]
It is a really easy fix.  Edit the udemy-dl.py file in C:\Python34\Lib\site-packages\udemy_dl.
Under def get_csrf_token():
Change the response line from:
response = session.get('https://www.udemy.com/join/login-popup')

to this:
response = session.get('https://www.udemy.com/join/login-submit')

and save it and try running it again.

**Comment by ozgurdemirel** [comment]
its still continue

**Comment by sinip1** [comment]
I tried runner989's solution and I get this after invoking udemy-dl.py:

E:\UDEMY>udemy-dl
Traceback (most recent call last):
  File "D:\Python34\Scripts\udemy-dl.py", line 4, in <module>
    from udemy_dl.udemy_dl import main
  File "D:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 40
    match = re.search('name="csrf" value="(.*)"', response.text)
                                                               ^
IndentationError: unindent does not match any outer indentation level

**Comment by sinip1** [comment]
OK, disregard previous post. I've managed to chaneg it but if I run it it looks like it will be going well, then this:

Traceback (most recent call last):
  File "D:\Python34\Scripts\udemy-dl.py", line 5, in <module>
    main()
  File "D:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 195, in main
    udemy_dl(username, password, link, output_dir)
  File "D:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 142, in udemy_
dl
    login(username, password)
  File "D:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 45, in login
    csrf_token = get_csrf_token()
  File "D:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 41, in get_csr
f_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by NANO-Chile** [comment]
After editing Im getting this error too:

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by runner989** [comment]
Udemy changed their login pages again.  Now the csrf token matching is different.  After changing the response line back to the original login page and changing the match line to this:
match = re.search("csrf: \'(.*)\'", response.text)

I am getting the following error:
Traceback (most recent call last):
  File "C:\Python34\Scripts\udemy-dl.py", line 5, in <module>
    main()
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 205, in main
    udemy_dl(username, password, link, output_dir)
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 152, in udemy_dl
    login(username, password)
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 64, in login
    response = response.json()
  File "C:\Python34\lib\site-packages\requests\models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by NANO-Chile** [comment]
and gaganpreet? :(

**Comment by finalight** [comment]
so any solutions yet?

**Comment by namaljayathunga** [comment]
Please, fix this very soon! :(

**Comment by finalight** [comment]
@runner989 the form url didn't change at all, it's still https://www.udemy.com/join/login-popup/ from what i can see in the webview

it's the name of the csrf token that's change, should be this "csrfmiddlewaretoken"

**Comment by nishad** [comment]
@finalight 
https://github.com/gaganpreet/udemy-dl/issues/75#issuecomment-121135516
and it should be `'csrfmiddlewaretoken'` not `"csrfmiddlewaretoken"`.
All the best.

**Comment by bajeesh** [comment]
https://www.udemy.com/join/login-submit is changed by udemy
login submit will not work

**Comment by nishad** [comment]
@bajeesh 
it should be `https://www.udemy.com/join/login-popup/` itself.

**Comment by bajeesh** [comment]
using the following regex to retrieve csrfmiddleware token 

"//input[@type=\"hidden\" and @name=\'csrfmiddlewaretoken\']"

and passing the token to
https://www.udemy.com/join/login-popup

STILL NOT WROKING

please help me..

**Comment by bajeesh** [comment]
@nishad 

Is it working for you.

**Comment by finalight** [comment]
you need to pass in a value for the csrfmiddlewaretoken

from the source code at the udemy login site, this is the type of value you need to pass in

<input type="hidden" name="csrfmiddlewaretoken" value="llgCaOjioNX48z4Y2zJGOnRvD8JdR2yS">

not sure what kind of value is that, don't think it's base 64 though

**Comment by nishad** [comment]
@bajeesh, I am not using `udemy-dl`. I am using a custom script in another language. Whenever my script fails, I check this repository for easy fixes since the login method is almost same. I've shared most of the similar solutions here in this thread. And yes, my script works.

**Comment by finalight** [comment]
let me try to do a pull request and see how is it

**Comment by finalight** [comment]
okay, done it but I don'tknow how to use github well so...I don't know how to deploy to the author pull requests

**Comment by bajeesh** [comment]
@finalight 
i changed code as per above fix, still not working..
Need any other  changes?

**Comment by finalight** [comment]
is it the same error?

**Comment by nishad** [comment]
@bajeesh, @finalight I've mentioned the issues at https://github.com/finalight/udemy-dl/commit/fea163d51c18d5993382d08bf14ec92be7f24da1#commitcomment-12196280 and https://github.com/finalight/udemy-dl/commit/fea163d51c18d5993382d08bf14ec92be7f24da1#commitcomment-12196280
All the best

**Comment by finalight** [comment]
@bajeesh i have updated the fix, please remerge it thanks

**Comment by bajeesh** [comment]
@finalight 
i tried the latest script, iam getting following error

Traceback (most recent call last):
  File "/var/www/test/udemy_dl.py", line 199, in <module>
    main()
  File "/var/www/test/udemy_dl.py", line 195, in main
    udemy_dl(username, password, link, output_dir)
  File "/var/www/test/udemy_dl.py", line 142, in udemy_dl
    login(username, password)
  File "/var/www/test/udemy_dl.py", line 54, in login
    response = response.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 6 column 1 (char 5)

**Comment by finalight** [comment]
not sure what's this error about though

**Comment by nishad** [comment]
Here is a quick fix since @gaganpreet is unavailable. This will work for now, and download your courses as soon as possible. Seems like Udemy engineers are also observing this thread for fixing the loopholes. :laughing: 

https://github.com/nishad/udemy-dl/commit/bc098a83140a3902919a9ea1da66147860f2ba4c

**Comment by finalight** [comment]
@nishad thanks for the fix, i was debugging and found out that my form post could work but it keep returning 403 response for some reason. Seems like you have found the reason for it

**Comment by convexset** [comment]
No reason for Udemy prevent downloads. Those who paid for the content should be able to download it. They own the rights.

**Comment by finalight** [comment]
@gaganpreet can merge the request done by @nishad ?? thanks

**Comment by nishad** [comment]
@convexset, it's not Udemy but the instructors are the decision makers on downloads. Personally I'm not against Udemy's policy. Since we are purchasing the course by knowing the limitation there's nothing much to blame Udemy, after all it is a life long subscription.

https://support.udemy.com/customer/portal/articles/1497278-can-i-download-a-course-to-my-computer-?b_id=3149

**Comment by bajeesh** [comment]
@nishad 
your fix doesn't seems to work. Are you sure is it working?

udemy login does not work. without login download is impossible.

**Comment by finalight** [comment]
@bajeesh his code works

tried it and i can download the udemy courses' videos already

**Comment by ozgurdemirel** [comment]
@nishad thx it works

**Comment by badershs** [comment]
Hi i have the script on my Ubuntu server any one knows the  path of file which i must edit it ? ?

**Comment by namaljayathunga** [comment]
wow, Its work. Thanks @nishad

**Comment by AbdulRaouf** [comment]
@nishad 
i tried latest script but i am getting the following error

File "/var/www/test/udemy_dl.py", line 201, in <module>
    main()
  File "/var/www/test/udemy_dl.py", line 197, in main
    udemy_dl(username, password, link, output_dir)
  File "/var/www/test/udemy_dl.py", line 151, in udemy_dl
    for video in get_video_links(course_id, hd=True):
  File "/var/www/test/udemy_dl.py", line 102, in get_video_links
    if item['__class'] == 'chapter':
TypeError: string indices must be integers

**Comment by nishad** [comment]
@badershs, I don't recommend editing the existing pip package since @gaganpreet is maintaining it. I just created an old fashioned standalone script. get it from 
https://github.com/nishad/udemy-dl/tree/standalone

```
python udemy-dl.py https://www.udemy.com/COURSE_NAME
```
Please wait for the updated version of the python package `udemy-dl`, since you got it installed all Python dependencies were already installed.

**Comment by badershs** [comment]
thanks i used your virsion i copy it and past it but it's not working 
 File "udemy-dl.py", line 242, in <module>
    main()
  File "udemy-dl.py", line 238, in main
    udemy_dl(username, password, link, output_dir)
  File "udemy-dl.py", line 192, in udemy_dl
    for video in get_video_links(course_id, hd=True):
  File "udemy-dl.py", line 143, in get_video_links
    if item['__class'] == 'chapter':
TypeError: string indices must be integers

**Comment by yoonwaiyan** [comment]
@nishad 's fork works for me. Thank you very much! Hope there's an update on this repo very soon.

**Comment by bajeesh** [comment]
@nishad 
As per latest update, instead of  'response = response.json()' using  'response.text', how you are using text content instead of json format.

iam using Python 2.7,  Do i need to upgrade my Python to work latest update.

**Comment by nishad** [comment]
@bajeesh, as I've mentioned in https://github.com/gaganpreet/udemy-dl/issues/75#issuecomment-121848095, I'm not using `udemy-dl`. I was moved by a couple of users' efforts to fix, so I shared my observations and finally a dirty fix for the time being. I don't have any plans to support it or carry over `udemy-dl`'s development. Please don't consider my fix as an update for `udemy-dl`. It should work if your `udemy-dl` was working, irrespective of the Python version.

Since `https://www.udemy.com/join/login-popup` is not generating any json output instead an html chunk `<div class="run-command close-popup redirect" data-url="/courses/"></div>`. `response.text` is the only option to catch the response. `'displayType': 'json'` doent have any effect, but I just kept it there as long as it doesn't affect the primary purpose of downloading videos.

Cheers

**Comment by raouf30** [comment]
@nishad thanks for the inputs. I was looking at this with @bajeesh.

Yes agree, but problem we are getting is that we are not able to login in first place :( . If we can login then we can parse the output as you mentioned.)

we will try again tommorow.

**Comment by nishad** [comment]
@raouf30, @bajeesh , @badershs, @AbdulRaouf, 
I'm sorry that I couldn't support you much on your issues. But some easy steps for linux is 

```
pip install udemy-dl
wget https://raw.githubusercontent.com/nishad/udemy-dl/standalone/udemy-dl.py
python udemy-dl.py https://www.udemy.com/COURSE_NAME
```
This works in Linux and Mac (if `wget` is installed, else for mac the second line should be `curl https://raw.githubusercontent.com/nishad/udemy-dl/standalone/udemy-dl.py -o udemy-dl.py`).

Unfortunately I'm not in a position to test this in windows.

Cheers

**Comment by raouf30** [comment]
many thanks @nishad  it does work on mac. just tested now. will check windows/linux.

**Comment by badershs** [comment]
i did it on linux it's not working 

Traceback (most recent call last):

  File "udemy-dl.py", line 242, in <module>
    main()
  File "udemy-dl.py", line 238, in main
    udemy_dl(username, password, link, output_dir)
  File "udemy-dl.py", line 192, in udemy_dl
    for video in get_video_links(course_id, hd=True):
  File "udemy-dl.py", line 143, in get_video_links
    if item['__class'] == 'chapter':
TypeError: string indices must be integers

**Comment by raouf30** [comment]
@badershs did you try curl https://raw.githubusercontent.com/nishad/udemy-dl/standalone/udemy-dl.py -o udemy-dl.py ? that worked,

**Comment by badershs** [comment]
what i did is 
pip install udemy-dl
then 
wget https://raw.githubusercontent.com/nishad/udemy-dl/standalone/udemy-dl.py
then python udemy-dl.py https://www.udemy.com/COURSE_NAME
and my email and password 
but i still had the same error 

Downloading to: /var/www/html/pythonforbeginnersintro

Traceback (most recent call last):
  File "udemy-dl.py", line 242, in <module>
    main()
  File "udemy-dl.py", line 238, in main
    udemy_dl(username, password, link, output_dir)
  File "udemy-dl.py", line 192, in udemy_dl
    for video in get_video_links(course_id, hd=True):
  File "udemy-dl.py", line 143, in get_video_links
    if item['__class'] == 'chapter':
TypeError: string indices must be integers

**Comment by runner989** [comment]
Same error on Windows as well:
Traceback (most recent call last):
  File "C:\Python34\Scripts\udemy-dl.py", line 5, in <module>
    main()
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 210, in main
    udemy_dl(username, password, link, output_dir)
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 164, in udemy_dl
    for video in get_video_links(course_id, hd=True):
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 115, in get_video_links
    if item['__class'] == 'chapter':
TypeError: string indices must be integers

Udemy appears to have changed how the Chapters are displayed or something.

**Comment by runner989** [comment]
Trying to debug what is occurring, I added a print statement to print out the value of "course_data" in the "get_video_links" routine.  Which returns the following:  

{'error': {'code': 401, 'message': 'Unauthorized - No Client', 'details': ''}}

I am assuming this means authentication is failing?

**Comment by badershs** [comment]
i dont think so 
if you said it's working on mac  and , both has the same code 
then the problem not from udemy there is some thing

**Comment by badershs** [comment]
@runner989 yes that what i think also 
we have  authentication problem not some thing else

**Comment by raouf30** [comment]
But how does it work for me on Mac and for others?

I will try on windows tomrw

**Comment by NANO-Chile** [comment]
I can confirm that using the udemy-dl from Nishad the script is working (in ubuntu linux)

python udemy-dl.py https://www.udemy.com/COURSE_NAME

Thanks for this dirty and great fix! :)

**Comment by badershs** [comment]
@NANO-Chile could you give your full steps  ? please ?

**Comment by raouf30** [comment]
Is it some Python version or some other dependan u causing problem in some environments ?

**Comment by runner989** [comment]
@nishad script is working.  I deleted my original udemy-dl.py from the site-packages folder (actually just renamed it) and took Nishad's script and put it there and it is working.  I'll have to do a side by side comparison to see what the differences are between the original code I had and the new code I just downloaded.

**Comment by raouf30** [comment]
That's exactly what I did to get it working as well. Need to do a diff and see

**Comment by badershs** [comment]
is this what did you use now ? @raouf30

**Comment by NANO-Chile** [comment]
I just did this steps:

pip install udemy-dl
wget https://raw.githubusercontent.com/nishad/udemy-dl/standalone/udemy-dl.py
python udemy-dl.py https://www.udemy.com/COURSE_NAME

the pip install udemy-dl says that I already have the files... so with wget I get the udemy-dl.py modified by Nishad and with the python command I call the script.

Im downloading courses without problem right now.

**Comment by badershs** [comment]
it's not work with me 
which python version do you use ?

**Comment by raouf30** [comment]
Yes

**Comment by NANO-Chile** [comment]
@badershs python 2.7.6

**Comment by badershs** [comment]
-_- me to 
that so strange

**Comment by NANO-Chile** [comment]
Im using VPS, with CentOS I had troubles so I moved to Ubuntu, no more problems :dart:

**Comment by badershs** [comment]
yes me too i'm using Ubuntu VPS also

**Comment by runner989** [comment]
I am using Windows Python version 3.4.3 and running the script through PowerShell.

**Comment by sinip1** [comment]
Ok so I have it running in Windows 7 x64 with Python 3.4.2 in an "as usual" way. I've just renamed it to python-dl1.py and invoke it like that with the trailing url to the course. It works perfectly! Thanks a lot.

**Comment by badershs** [comment]
itsssssss work finaly :+1: 
i drop it my vbs ubuntu and rebuild 32 version my last version was 64x

**Comment by finalight** [comment]
if possible please update the pip package, so I no need to keep an extra copy of the udemy-dl folder

**Comment by jcrawford** [comment]
it appears Udemy changed the name of the token element from csrf to csrfmiddlewaretoken

You can see the code that needs changing here: https://github.com/gaganpreet/udemy-dl/blob/master/src/udemy_dl/udemy_dl.py#L40

If you cannot modify your local install then wait for the developer to release a fixed version.

**Comment by AbdulRaouf** [comment]
i have done following steps...
pip install udemy-dl
wget https://raw.githubusercontent.com/nishad/udemy-dl/standalone/udemy-dl.py
python udemy-dl.py https://www.udemy.com/COURSE_NAME

but still same error....

Traceback (most recent call last):
  File "udemy-dl.py", line 242, in <module>
    main()
  File "udemy-dl.py", line 238, in main
    udemy_dl(username, password, link, output_dir)
  File "udemy-dl.py", line 192, in udemy_dl
    for video in get_video_links(course_id, hd=True):
  File "udemy-dl.py", line 143, in get_video_links
    if item['__class'] == 'chapter':
TypeError: string indices must be integers

**Comment by namaljayathunga** [comment]
@AbdulRaouf 
I do thees steps in widows.
pip uninstall udemy-dl
pip install udemy-dl

find C:\Python34\Lib\site-packages\udemy_dl\udemy-dl.py
[do thees changes](https://github.com/nishad/udemy-dl/commit/bc098a83140a3902919a9ea1da66147860f2ba4c)
or replace with [https://raw.githubusercontent.com/nishad/udemy-dl/standalone/udemy-dl.py](https://raw.githubusercontent.com/nishad/udemy-dl/standalone/udemy-dl.py)
Boom!
Thanks to @nishad

**Comment by AbdulRaouf** [comment]
@namaljayathunga 
i am using latest script...but still same error

**Comment by nishad** [comment]
I'm sorry that most of you guys are still struggling with the script. Since I am not in a position to fix everyone's issues, here is a quick solution. I've created a windows standalone `udemy-dl.exe`. You dont need to install python or nothing like that. Just run `udemy-dl.exe` instead `udemy-dl.py`. 

https://github.com/nishad/udemy-dl/releases/download/0.1.5.alpha.3/udemy-dl_0.1.5_win32_alpha_3.zip

The repository tree is here https://github.com/nishad/udemy-dl/tree/win32.

Please note: These files are **only for windows**, It is just a short time solution till @gaganpreet updates his python package. Probably I wont get enough time to maintain or support this tool. So go back to `udemy-dl` when there is a fix available.

Happy Udemying, Cheers :sake:

**Comment by NANO-Chile** [comment]
@nishad  Im not using the Windows version, but your a hero for many people, I have to say! Great work mate!

Regards!

**Comment by raouf30** [comment]
@nishad you are a star yes. your script works on windows 32.

(on  windows 64 doesn't seem to work. ah well. will try to find the reason. i guess this is the probably error most are getting.)

**Comment by nishad** [comment]
@raouf30, the fun fact is this exe is generated in a 64bit Windows 7, with a 32bit Python 2.7.x, It was passing all tests, and I've never tested it in a 32bit windows :laughing:

**Comment by raouf30** [comment]
😄 Tried on another machine in 64 bit and worked. So strange.

**Comment by raouf30** [comment]
So some combination it doesn't work mainly 64bit

**Comment by nishad** [comment]
@raouf30, what do you mean by combination ?

**Comment by raouf30** [comment]
@nishad some win 64bit machines it works - some it doesn't . I also had a c# sample that does same thing and that also doesn't seem to work. I need to do more checks to see what exact combination.

**Comment by namaljayathunga** [comment]
@nishad I tried to download 3 courses in one hour. but there was error. when I tried to login to udemy, gave this massage "You have exceeded the maximum number of requests per hour." I think this is because udemy-dl should login again and again to download each courses. can you modify this script to get courses parameter by array list, then one login and download more courses. Thanks

**Comment by chiqui3d** [comment]
Hello @nishad 
Is there no solution? I have ubuntu 14.04 (64 bit) and pip from /usr/lib/python2.7/dist-packages 1.5.4 (python 2.7). And the error I get is the following:
```python
Traceback (most recent call last):
  File "udemy-dl.py", line 242, in <module>
    main()
  File "udemy-dl.py", line 238, in main
    udemy_dl(username, password, link, output_dir)
  File "udemy-dl.py", line 192, in udemy_dl
    for video in get_video_links(course_id, hd=True):
  File "udemy-dl.py", line 143, in get_video_links
    if item['__class'] == 'chapter':
TypeError: string indices must be integers
```

thanks!!

**Comment by visionclick** [comment]
@nishad Please help us. I have same problem that @chiqui3d

**Comment by nishad** [comment]
@namaljayathunga, your issues is different from https://github.com/gaganpreet/udemy-dl/issues/75, and it got nothing to do with `udemy-dl` as well. Udemy limits number of `requests` per hour. `udemy-dl` uses a single session for a complete course. So there is no multiple login. All you need to do is **wait or give sufficient time gap** between your downloads, specially if you are downloading large courses with lot of chapters though a high-speed internet connection. Next time please open a new issue if your problem is something else other than any opened issue instead of reopening a closed issue.

**Comment by nishad** [comment]
@chiqui3d @visionclick, your issue is also different from https://github.com/gaganpreet/udemy-dl/issues/75, so please open another issue instead of reopening this thread.
