### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by VincyLouis** [gaganpreet/udemy-dl#78]
Hi, 

There is a error, it didn't happen before when i first use

Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 195, in main
    udemy_dl(username, password, link, output_dir)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 142, in udemy_dl
    login(username, password)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 45, in login
    csrf_token = get_csrf_token()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 41, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by namaljayathunga** [comment]
I tried to download 3 courses in one hour. but there was error. when I tried to login to udemy, gave this massage "You have exceeded the maximum number of requests per hour." I think this is because udemy-dl should login again and again to download each courses. udemy-dl can modify to get courses parameter by array list, then one login and download more courses. Thanks

**Comment by hfchdf** [comment]
Uninstall any Microsoft Visual

**Comment by msj2** [comment]
The above Issue  .. "AttributeError: 'NoneType' object has no attribute 'group'" is still present, while using udemy-dl on Ubuntu 14.

**Comment by VincyLouis** [comment]
no microsoft visual found in mac, issue still not fix yet

**Comment by ILegendI** [comment]
Do Update the script which gaganpereet upgrade script for udemy changes if you dont you will always get this error.

**Comment by VincyLouis** [comment]
Sorry, I did't know how to update the script, but sudo uninstall and install and it works again, Thanks @ILegendl

**Comment by ILegendI** [comment]
Not problem also you can upgrade with editing the .py file with some text editor.
