### ISSUE TITLE
command not found: udemy-dl

### ISSUE THREAD

**Issue by finalight** [gaganpreet/udemy-dl#79]
i uninstall udemy-dl 

and then reinstall it

apparently it gave me the above error

any idea on how to solve it?

**Comment by msj2** [comment]
I want to add to this, Feel free to denounce me as dumb, but I need help.

I am new to Windows (WIndows 8.1)
I installed Python 2.7
Then installed PIP
then used these commands to get udemy-dl running.
pip install requests
pip install udemy-dl 


I expected udemy-dl to be a valid shell command now.
But, when I enter udemy-dl, I get the error finalight encountered.

command not found: udemy-dl

Kidnly help me, how to use udemy-dl on windows 8.1

**Comment by finalight** [comment]
mine is mac osx, yosemite

on my ubuntu is okay, but mac it doesn't work

**Comment by otezz** [comment]
Try renaming udemy-dl to udemy-dl.py in the Scripts folder. It works for me on win 10

**Comment by gaganpreet** [comment]
If you are using Windows look at #60, you might get some idea how to make it work.

**Comment by finalight** [comment]
nope i'm using mac osx
