### ISSUE TITLE
Convert code into c#

### ISSUE THREAD

**Issue by AbdulRaouf** [gaganpreet/udemy-dl#82]
Hi,

I am trying same code in c#, but  Udemy log in failed in c#

Please help me to fix this issue. Anybody converted python code to c#.

Thanks,

**Comment by ILegendI** [comment]
İf You want windows 32 bit version ı can link you someones projects but ı dont what language use he to write it.

**Comment by AbdulRaouf** [comment]
@ILegendI 
can you please give me the links

**Comment by ILegendI** [comment]
@AbdulRaouf  There You go.

https://github.com/nishad/udemy-dl/tree/win32
