### ISSUE TITLE
Udemy Updated - Login form is updated 

### ISSUE THREAD

**Issue by Lulzpedia** [gaganpreet/udemy-dl#83]
Hello,

Problem with the script

Traceback (most recent call last):
  File "udemy-dl.py", line 175, in <module>
    main()
  File "udemy-dl.py", line 171, in main
    udemy_dl(username, password, link)
  File "udemy-dl.py", line 134, in udemy_dl
    login(username, password)
  File "udemy-dl.py", line 45, in login
    csrf_token = get_csrf_token()
  File "udemy-dl.py", line 40, in get_csrf_token
    return soup.find_all('input', {'name': 'csrf'})[0]['value']
IndexError: list index out of range

I think udemy updated the login form can u please update the code

**Comment by ILegendI** [comment]
I think Udemy Managers also folowing gaganpereet's  script :facepunch:

**Comment by Lulzpedia** [comment]
Waiting for the author to update the script

**Comment by ILegendI** [comment]
I Find What Udemy Changed Udemy Changed Login Submit link to .js this is problem i think but gaganpereet can do it i think.

**Comment by gaganpreet** [comment]
You're on an older version already, the dependency on BeautifulSoup was removed months ago.

**Comment by Lulzpedia** [comment]
@gaganpreet did't got it ? I'm using the latest version of your script.Just downloaded yesterday check it kindly

**Comment by Lulzpedia** [comment]
@gaganpreet 

![2015-08-01_1941](https://cloud.githubusercontent.com/assets/13573124/9022193/86272f1a-3885-11e5-90c1-fba11a52195c.png)

**Comment by gaganpreet** [comment]
This error can only be from an older version of udemy-dl, and you aren't on the latest version.

**Comment by Lulzpedia** [comment]
@gaganpreet I'm using the latest version Brother.Can u please give me the link for updated one or you can please check the tool [ For confirmation ]

**Comment by nishad** [comment]
@Lulzpedia, don't be stubborn my friend. As gaganpreet said, you are not using the latest version.
```python
return soup.find_all('input',{'name':'csrf'})[0][`value`]
```
this line in your screenshot says it uses a python package BeautifulSoup, which is no more used in `udemy-dl`. 

Latest version is available here, https://github.com/gaganpreet/udemy-dl. 

Please try to follow the instructions available at that page, instead reopening this closed thread.

**Comment by Lulzpedia** [comment]
Solved it Thanks

**Comment by nishad** [comment]
@gaganpreet, Could you create a release for `0.1.7`. It seems like people are getting confused since the new release is not showing up there.

**Comment by gaganpreet** [comment]
@nishad I don't get what you mean - the version on PyPI  is 0.1.7 which is the latest one from master branch.

**Comment by nishad** [comment]
@gaganpreet, I mean a github release as well. https://github.com/gaganpreet/udemy-dl/releases
There is no release after `0.1.5`. Which will be confusing for people trying to install from source instead `pip`.

**Comment by gaganpreet** [comment]
Done! Thanks for the heads up.
