### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by hamzaom675** [gaganpreet/udemy-dl#86]
hi

**Comment by georgeappiah** [comment]
Of course this will only work within the 5-minute window when you have free access. Most courses will tame much longer than 5 minutes to download.

**Comment by nishad** [comment]
There's an ethical reason behind this tool. Anything beyond that, will not be entertained or encouraged to be related with this tool. We should also respect Udemy and its author's rights and business model.
Happy Udemying

**Comment by gaganpreet** [comment]
There's a reason the description of this script says it is "for personal offline use". This script wasn't and will never be meant to be used for piracy.
