### ISSUE TITLE
Lecture Start and Lecture End Parameters Don't Correspond

### ISSUE THREAD

**Issue by josephkandi** [gaganpreet/udemy-dl#87]
The `--lecture-start`and `--lecture-end` parameters do not correspond to the udemy lecture numbers. The script does not count the non-video lectures resulting in incorrect lecture start and end numbers. It would be nice if the parameters correspond but they do skip the non-video course links.

**Comment by Lulzpedia** [comment]
Its working fine man.Update to the latest version use the video number you see on udemy course.

**Comment by josephkandi** [comment]
Thanks
